.github/workflows/jan-docs.yml

CI release to github page trigger on release branch

---

docusaurus.config.js
yarn.lock

chore: migrate new docs 

---

README.md
docusaurus.config.js
src/containers/Testimonial/index.js
static/robots.txt

fix: no index youtube iframe

---

tailwind.config.js

fix: change josefin into PPEditorialNew font

---

.github/workflows/jan-docs.yml

jan.ai trigger by main branch
- Closes #
- Closes #

jan.ai trigger by main branch

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/discussion-thread.md
.github/ISSUE_TEMPLATE/documentation-request.md
.github/ISSUE_TEMPLATE/epic-request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.github/workflows/auto-assign-author.yml
.github/workflows/auto-label-conventional-commits.yaml
.github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
.github/workflows/jan-docs.yml
next.config.mjs

- Update CICD for nextra
- Closes #
- Closes #

Update CICD for nextra

---

docs/acknowledgements.md

- Please auto merge for me thank you
- Closes #
- Closes #

docs: Update acknowledgements.md

---

docs/about/about.md
docs/about/faq.md
docs/acknowledgements.md
docs/privacy/privacy.md

- please automerge for me
- Closes #
- Closes #

docs: acks

---

docs/guides/user-guides/manage-models.mdx
sidebars.js

- pls edit and automerge for me
- Closes #
- Closes #

add manage models page

---

docs/guides/user-guides/advanced-settings.mdx
docs/guides/user-guides/jan-data-folder.mdx
docs/guides/user-guides/local-server.mdx
docs/guides/user-guides/manage-assistants.mdx
docs/guides/user-guides/manage-models.mdx
docs/guides/user-guides/manage-threads.mdx
docs/guides/user-guides/overview-guides.mdx
docs/guides/user-guides/use-tools.mdx
sidebars.js

- pls edit and auto merge for me
- manage assistants
- rag
- Closes #
- Closes #

add docs for rag and manage asst

---

openapi/jan.json

- Added a note in the JSON file for the 4.10 release: https://github.com/janhq/jan/issues/2512
- Closes #

docs: Updated the openapi json

---

src/components/APIReference/index.tsx
src/pages/about/_meta.json
src/pages/about/teams/_meta.json

fix: update missing path scalar json

---

.env

fix: remove env

---

src/pages/_meta.json

fix: type of page

---

src/pages/_app.mdx

fix: missing gtmid format

---

_redirects

-  Update redirect
- Closes #
- Closes #

docs: Update redirect

---

src/components/Blog/index.tsx
src/components/Changelog/index.tsx
src/components/Download/CardDownload.tsx
src/components/FooterMenu/index.tsx
src/components/Home/BuiltWithLove/index.tsx
src/components/Home/CTANewsletter/index.tsx
src/components/Home/Feature/index.tsx
src/components/Home/Principles/index.tsx
src/pages/_meta.json
src/styles/general.scss
theme.config.tsx

fix: resolve github broken link

---

_redirects

- Redirect broken link `/troubleshootin`
- Add redirect link 
- Closes #
- Closes #

docs: Fix redirect broken linsks

---

src/pages/about/_meta.json

fix: wrong _meta.json about folder

---

src/components/APIReference/index.tsx
src/components/Blog/index.tsx

fix: scalar system theme

---

package.json
yarn.lock

- Update the `@Scalar` dependencies from  `^0.1.19`  →  `^0.1.31`
- Closes #
- Closes #

docs: Updated the Scalar dependencies to fix the response schema ui

---

src/pages/docs/local-inference/llamacpp.mdx

docs: Update llamacpp.mdx

---

src/components/DropdownDownload/index.tsx

fix: missing link url default system download button

---

src/components/Home/CTADownload/index.tsx
src/components/Home/Hero/index.tsx
src/components/Home/Statistic/index.tsx

- Docs: Update a new website statistics
- Closes #
- Closes #

docs: Update website stat

---

src/pages/docs/extensions.mdx

- Added a section to explain the new app logging settings for v4.11 release https://github.com/janhq/jan/issues/2627
- Closes #
- Closes #
- [x ] Updated docs (for bug fixes / features)

docs: added the section for the app logging settings

---

src/pages/docs/models.mdx

- Updated the Using Models page.
- Closes #
- Closes #
- [ x] Updated docs (for bug fixes / features)

docs: updated the Using Models page.

---

src/components/Home/APIStructure/index.tsx

fix: update typo

---

_redirects

- Update redirect to fix broken links
- Closes #
- Closes #

docs: Update redirects to fix broken link

---

src/pages/blog.mdx

fix: client side error on blog page

---

src/pages/docs/_meta.json
src/pages/docs/extensions.mdx
src/pages/docs/hardware-setup.mdx
src/pages/docs/installation/desktop.mdx
src/pages/docs/installation/server.mdx
src/pages/docs/integrations/discord.mdx
src/pages/docs/integrations/interpreter.mdx
src/pages/docs/integrations/vscode.mdx
src/pages/docs/local-inference/llamacpp.mdx
src/pages/docs/models.mdx
src/pages/docs/remote-inference/groq.mdx
src/pages/docs/remote-inference/mistralai.mdx
src/pages/docs/remote-inference/openai.mdx
src/pages/docs/troubleshooting.mdx

- Updated the docs
- Closes #
- Closes #

docs: Updated the docs

---

src/components/FooterMenu/index.tsx

feat: update copies footer

---

src/components/Home/Feature/index.tsx

-
- [issue](https://discord.com/channels/1107178041848909847/1231864479264800898/1231864481118949428)

fix: update copy remote api feature

---

src/pages/integrations/messaging/discord.mdx

Hello, I'm the creator of llmcord.py and wanted to help improve its docs :)
- Better description of llmcord.py
- Added new callout in step 2: "A valid Python installation is required." 
- Simplified config option section
- Simplified bot invite URL instructions

integrations: improve Discord bot instructions

---

src/pages/docs/quickstart.mdx
src/pages/docs/server-installation.mdx

-Updated the quickstart redirect links
- Closes #
- Closes #

docs: Updated the quickstart redirect links

---

src/components/Home/CTADownload/index.tsx
src/components/Home/Hero/index.tsx
src/components/Home/Statistic/index.tsx

- Manually update stats from the analytics metrics
- Closes #
- Closes #

docs: manually update stats

---

src/pages/changelog.mdx

fix: changelog invalid time

---

_redirects

- Updated the redirect links
- Closes #
- Closes #

docs: Updated the redirect links

---

theme.config.tsx

fix: fetch redirect og:image

---

src/pages/docs/index.mdx
src/pages/privacy.mdx

update to correct privacy policy

---

_redirects
src/pages/docs/built-in/llama-cpp.mdx
src/pages/docs/models/manage-models.mdx
src/pages/docs/server-installation/onprem.mdx

- Update to reflect the new app behavior
- https://github.com/janhq/jan/issues/2859
- Closes #

docs: Update to reflect the new app behavior

---

src/components/FooterMenu/index.tsx

fix: update copyright footer

---

src/pages/about/index.mdx

Small changes to About Page
- Shout out to Homebrew Computer Club
- Simplify self-description

Small changes to About Page

---

src/pages/cortex/index.mdx
src/pages/docs/desktop/linux.mdx
src/pages/docs/desktop/mac.mdx
src/pages/docs/desktop/windows.mdx

- Added the cortex callout
- Update the desktop installation compatibility into tabs
- Closes #
- Closes #

docs: added the cortex callout and update the hardware into tabs

---

src/components/Download/index.tsx
src/components/Home/Hero/index.tsx
src/components/Home/Statistic/index.tsx
src/components/ImageCaption/index.tsx
src/pages/docs/index.mdx

- Added image caption component 
how to use 
`example on your file .mdx`
`example render on browser`
- Closes #
- Closes #

feat: create image caption component

---

src/pages/cortex/quickstart.mdx

- nits, 
- Closes #
- Closes #

docs: Update quickstart.mdx

---

public/openapi/jan.json

- Update the json file to match the new Cortex API
- Closes #
- Closes #

docs: Update the API Reference file

---

public/openapi/jan.json

- Update the API file
- Closes #
- Closes #

docs: Update the API swagger file

---

src/components/APIReference/index.tsx
yarn.lock

- Use the  `hideModels` feature to fix the schemas shown in the API reference documents.
- Closes #
- Closes #

API: hide models

---

public/openapi/jan.json

- Update the URL to 1337
- Closes #
- Closes #

API: update the server URL

---

public/openapi/jan.json

- added the get thread response
- Closes #
- Closes #

API: Added the get thread response

---

src/pages/cortex/cli/pull.mdx
src/pages/cortex/quickstart.mdx

- Update the cortex pull page to reflect the quickstart
- Closes #
- Closes #

Update the cortex pull page

---

src/components/Home/BuiltWithLove/index.tsx
src/components/Home/CTADownload/index.tsx
src/components/Home/Hero/index.tsx
src/components/Home/Statistic/index.tsx
src/pages/about/_meta.json
src/pages/cortex/_meta.json
src/pages/index.mdx
src/utils/format.ts

- Update statistic total download from API github
- Update number with notation compac
- Closes #
- Closes #

feat: update total download from api github

---

src/pages/cortex/_meta.json
src/pages/cortex/cli.mdx
src/pages/cortex/cli/_meta.json
src/pages/cortex/cli/chat.mdx
src/pages/cortex/cli/init.mdx
src/pages/cortex/cli/models.mdx
src/pages/cortex/cli/models/_meta.json
src/pages/cortex/cli/models/download.mdx
src/pages/cortex/cli/models/get.mdx
src/pages/cortex/cli/models/list.mdx
src/pages/cortex/cli/models/remove.mdx
src/pages/cortex/cli/models/start.mdx
src/pages/cortex/cli/models/stop.mdx
src/pages/cortex/cli/pull.mdx
src/pages/cortex/cli/run.mdx
src/pages/cortex/cli/serve.mdx

- Revamp the CLI docs
- Add the pages for init and serve
- Closes #
- Closes #

docs: Revamp the CLI documentation

---

src/pages/_app.mdx

Fix setup Google Analytics
Verified using this extension 
https://chromewebstore.google.com/detail/debugger-for-google-analy/nomnoimacbncclfbnfaingniikblfbji?hl=en-US&utm_source=ext_sidebar

fix: setup analytics

---

src/pages/cortex/cli/models.mdx
src/pages/cortex/cli/models/_meta.json
src/pages/cortex/cli/models/update.mdx
src/pages/cortex/cli/pull.mdx

- Update the CLI pages
- Closes https://github.com/janhq/docs/issues/230
- Closes #

docs: Update the CLI pages

---

src/pages/docs/remote-models/_meta.json
src/pages/docs/remote-models/azure.mdx
src/pages/docs/remote-models/generic-openai.mdx

- Add the Azure OpenAI API page
- Add notes in the OpenAI, Azure and Generic OpenAI pages.
- Closes https://github.com/janhq/docs/issues/244
- Closes #

docs: Update the Remtoe APIs section

---

_redirects

- fix the generic openai url
- Closes #
- Closes #

docs: fix the URL

---

public/openapi/jan.json

- fix the schema URL
- Closes #
- Closes #

Fix the schema URL

---

public/openapi/jan.json
src/pages/cortex/_meta.json
src/pages/cortex/cli.mdx
src/pages/cortex/cli/_meta.json
src/pages/cortex/cli/chat.mdx
src/pages/cortex/cli/init.mdx
src/pages/cortex/cli/kill.mdx
src/pages/cortex/cli/models.mdx
src/pages/cortex/cli/models/download.mdx
src/pages/cortex/cli/models/get.mdx
src/pages/cortex/cli/models/list.mdx
src/pages/cortex/cli/models/remove.mdx
src/pages/cortex/cli/models/start.mdx
src/pages/cortex/cli/models/stop.mdx
src/pages/cortex/cli/models/update.mdx
src/pages/cortex/cli/ps.mdx
src/pages/cortex/cli/pull.mdx
src/pages/cortex/cli/run.mdx
src/pages/cortex/cli/serve.mdx

- Update the CLI commands
- Closes #
- Closes #

docs: Update the CLI commands

---

src/pages/cortex/cli.mdx

- update the cli overview
- Closes #
- Closes #

update the cli overview

---

src/pages/cortex/cli.mdx

docs: Update cortex download desc

---

src/pages/cortex/_meta.json
src/pages/cortex/architecture.mdx
src/pages/cortex/hardware.mdx
src/pages/cortex/quickstart.mdx
src/pages/cortex/server.mdx
src/pages/docs/quickstart.mdx

- see title
- Closes #
- Closes #

cortex: improve quickstart, add hardware reqs

---

src/pages/cortex/quickstart.mdx

- Quickstart revamp
- Closes #
- Closes #

docs: Quickstart revamp

---

src/pages/cortex/architecture.mdx

- Remove the links
- Closes #
- Closes #

docs: nits

---

_redirects

- Update the redirects
- Closes #
- Closes #

docs: Update the redirects

---

package.json
src/components/OAICoverage/index.tsx
src/pages/cortex/server.mdx
yarn.lock

feat: OAI coverage UI

---

_redirects

- Redirects Cortex
- Closes #
- Closes #

Redirects Cortex

---

src/components/DropdownDownload/index.tsx
src/components/Home/Hero/index.tsx

fix: conditional download button for apple m series or intel

---

src/pages/docs/built-in/llama-cpp.mdx
src/pages/docs/built-in/tensorrt-llm.mdx
src/pages/docs/desktop/linux.mdx
src/pages/docs/desktop/windows.mdx
src/pages/docs/local-api.mdx
src/pages/docs/models/manage-models.mdx
src/pages/docs/quickstart.mdx

- Update the docs
- Closes https://github.com/janhq/jan/issues/3123#event-13347531846
- Closes #

Update the docs

---

src/pages/docs/troubleshooting.mdx

- Update the Undefined Issue section
- Closes #
- Closes #

Update the Undefined Issue section

---

src/components/Home/Hero/index.tsx

fix: missing image hero section

---

src/components/FooterMenu/index.tsx
src/pages/about/index.mdx
theme.config.tsx

fix: update social media link

---

src/components/FooterMenu/index.tsx
src/pages/about/team.mdx
src/pages/docs/index.mdx

fix: career link

---

src/components/Home/APIStructure/index.tsx

fix: missing url api-reference

---

src/pages/docs/_meta.json
src/pages/docs/tools/retrieval.mdx

- Added the missing Retrieval
- Closes #
- Closes #

Added the missing Retrieval

---

src/pages/docs/settings.mdx

Vulcan -> Vulkan

---

src/pages/docs/data-folder.mdx

Update the Jan Data Folder page

---

src/pages/changelog/2024-09-01-llama3-1-gemma2-support.mdx

fix: latest changelog date

---

src/pages/changelog/2024-09-17-improved-cpu-performance.mdx

Create v0.5.4 changelog post

---

.github/workflows/jan-docs.yml

- ci: enable workflow dispatch for build docs pipeline
- Related ticket https://github.com/janhq/docs/issues/147

ci: enable workflow dispatch for build docs pipeline
